Keys, drupal update and two new sites
UTNkar/ansible pull request #1
Opened 2021-05-04 17:44 UTC by Antonfogelberg

Add two new sites. [mer.utn.se](mer.utn.se) and [engagemang.utn.se](engagemang.utn.se). 

Realizing ansible repo has not been updated in a while, Im a abit unsure if all these changes were needed?

2021-05-04 20:42 UTC, dakaza98 requested changes

2021-05-04 20:42 UTC, dakaza98 commented on vars/django/moore.yml
> +server_name: "utn.se www.utn.se apply.utn.se grus.utn.se sangbok.utn.se balen.utn.se forsranningen.utn.se rally.utn.se dv.utn.se es-dev.utn.se nvb.utn.se engagemang.utn.se mer.utn.se"
Are you making a completely new website for the engagemang wheel?

2021-05-04 20:42 UTC, dakaza98 commented on roles/django/tasks/deploy.yml
> +    settings: "{{ django_settings }}"
The update_index command can only be runned by moore since it is a command coming from wagtail https://docs.wagtail.io/en/stable/reference/management_commands.html#update-index. Other django instances will get an error if this is command is runned

2021-05-05 09:33 UTC, Antonfogelberg commented on vars/django/moore.yml
> +server_name: "utn.se www.utn.se apply.utn.se grus.utn.se sangbok.utn.se balen.utn.se forsranningen.utn.se rally.utn.se dv.utn.se es-dev.utn.se nvb.utn.se engagemang.utn.se mer.utn.se"
At the moment yes. We are hoping that it can replace or be implemented as a part of [Involvement](https://utn.se/involvement/). 
Probably a better idea to develop it as a page under one of the already existing.

2021-05-05 10:34 UTC, dakaza98 approved these changes

2021-05-05 10:35 UTC, merged